import { NextResponse } from "next/server";
import { execFile } from "child_process";
import { promisify } from "util";
import { mkdir, readFile, writeFile } from "fs/promises";
import path from "path";
import crypto from "crypto";
import ffmpegStatic from "ffmpeg-static";

export const runtime = "nodejs";
const execFileAsync = promisify(execFile);
const ffmpeg = ffmpegStatic || "ffmpeg";

type ClipInput={originalName:string;url:string;path?:string};
type TextOverlay={text:string;startSeconds:number;endSeconds:number;kind?:string;position?:string;style?:string;animation?:string};
type Sfx={timeSeconds:number;type:string;durationSeconds?:number;intensity?:number};
type Segment={clip:string;startSeconds:number;endSeconds:number;speed?:number;zoom?:number;zoomDirection?:string;isHero?:boolean;reason?:string};
type Plan={targetDurationSeconds?:number;aspectRatio?:string;hook?:string;hookEnabled?:boolean;clipSequence?:Segment[];textOverlays?:TextOverlay[];captions?:Array<{text:string;placement?:string;style?:string;startSeconds?:number;endSeconds?:number}>;audioDirection?:string;musicMood?:string;musicIntensity?:number;sfx?:Sfx[];colorPreset?:string;colorDirection?:string;transitions?:Array<{afterClip:string;type:string}>};

function safeFilename(value:string){return path.basename(value)}
function sourcePath(clip:ClipInput){if(clip.path)return path.join(process.cwd(),"data","uploads",safeFilename(path.basename(clip.path)));const url=new URL(clip.url,"http://editio.local");const name=url.searchParams.get("name")||safeFilename(url.pathname);if(!name||name.includes(".."))throw new Error("Invalid uploaded video reference.");return path.join(process.cwd(),"data","uploads",safeFilename(name));}
async function hasAudio(file:string){try{await execFileAsync(ffmpeg,["-v","error","-i",file,"-map","0:a:0","-f","null","-"]);return true}catch{return false}}
function clamp(n:number,min:number,max:number){return Math.max(min,Math.min(max,Number.isFinite(n)?n:min))}
function escText(text:string){return text.replace(/\\/g,"\\\\").replace(/:/g,"\\:").replace(/'/g,"\\'").replace(/%/g,"\\%").replace(/\[/g,"\\[").replace(/\]/g,"\\]").replace(/;/g,"\\;")}
function colorFilter(preset:string){switch(preset){case"crisp":return"eq=contrast=1.08:saturation=1.06:brightness=0.01";case"warm":return"eq=contrast=1.04:saturation=1.05:gamma_r=1.03:gamma_b=0.97";case"cinematic":return"eq=contrast=1.06:saturation=0.92:brightness=-0.01";case"punchy":return"eq=contrast=1.12:saturation=1.1:brightness=0.01";default:return"null"}}
function framingFilter(zoom:number,zoomDirection:string){const z=clamp(zoom,0.88,1.12);if(z>1.001||zoomDirection==="in"){const w=Math.round(1080*z);const h=Math.round(1920*z);return`scale=${w}:${h}:force_original_aspect_ratio=increase,crop=1080:1920:(iw-1080)/2:(ih-1920)/2`;}const fgW=Math.round(1080*z);const fgH=Math.round(1920*z);return`split=2[bg][fg];[bg]scale=1080:1920:force_original_aspect_ratio=increase,crop=1080:1920,boxblur=22:2[blur];[fg]scale=${fgW}:${fgH}:force_original_aspect_ratio=decrease[fit];[blur][fit]overlay=(W-w)/2:(H-h)/2`}
function transitionFilter(type:string,duration:number){if(type==="flash"||type==="white-flash")return`fade=t=out:st=${Math.max(0,duration-0.12).toFixed(3)}:d=0.12:color=white`;if(type==="fade")return`fade=t=out:st=${Math.max(0,duration-0.18).toFixed(3)}:d=0.18:color=black`;return"null"}
function videoFilter(segment:Segment,preset:string,transition:string|undefined,sourceDuration:number){const speed=clamp(Number(segment.speed??1),0.65,1.35);const filters=[framingFilter(Number(segment.zoom??1),segment.zoomDirection||"none")];const color=colorFilter(preset);if(color!=="null")filters.push(color);if(transition){const tf=transitionFilter(transition,sourceDuration/speed);if(tf!=="null")filters.push(tf)}filters.push(`setpts=PTS/${speed.toFixed(3)}`);return filters.join(",")}
function fontSpec(style:string){if(style==="cinematic")return{size:76,border:2,box:false};if(style==="funny")return{size:88,border:4,box:true};if(style==="sports")return{size:94,border:5,box:false};if(style==="clean")return{size:72,border:3,box:true};return{size:92,border:5,box:false}}
function textFilter(texts:TextOverlay[],totalDuration:number){let current="[0:v]";const filters:string[]=[];texts.slice(0,8).forEach((item,index)=>{const text=escText(item.text.trim().slice(0,70));if(!text)return;const start=clamp(Number(item.startSeconds||0),0,Math.max(0,totalDuration-0.05));const end=clamp(Number(item.endSeconds||start+1),start+0.2,totalDuration);const spec=fontSpec(item.style||"bold");const y=item.position==="top"?"h*0.13":item.position==="bottom"?"h*0.78":"h*0.45";const x=item.animation==="slide"?`if(lt(t,${(start+0.22).toFixed(3)}),w-(w-text_w)*(t-${start.toFixed(3)})/0.22,(w-text_w)/2)`:"(w-text_w)/2";const alpha=item.animation==="fade"||item.animation==="pop"?`if(lt(t,${(start+0.18).toFixed(3)}),(t-${start.toFixed(3)})/0.18,1)`:"1";const box=spec.box?":box=1:boxcolor=black@0.32:boxborderw=14":"";const out=`[txt${index}]`;filters.push(`${current}drawtext=font='DejaVu Sans':text='${text}':fontcolor=white:alpha='${alpha}':fontsize=${spec.size}:x=${x}:y=${y}:borderw=${spec.border}:bordercolor=black@0.72:enable='between(t,${start.toFixed(3)},${end.toFixed(3)})'${box}${out}`);current=out});if(!filters.length)return{graph:"[0:v]null[vout]",map:"[vout]"};return{graph:`${filters.join(";")};${current}null[vout]`,map:"[vout]"}}
function musicExpression(mood:string){switch(mood){case"hype":return"0.55*sin(2*PI*110*t)+0.22*sin(2*PI*220*t)+0.08*sin(2*PI*440*t)";case"cinematic":return"0.55*sin(2*PI*65*t)+0.18*sin(2*PI*130*t)+0.05*sin(2*PI*260*t)";case"chill":return"0.45*sin(2*PI*174*t)+0.16*sin(2*PI*261.63*t)+0.06*sin(2*PI*349.23*t)";case"funny":return"0.25*sin(2*PI*330*t)+0.18*sin(2*PI*495*t)+0.1*sin(2*PI*660*t)";case"emotional":return"0.4*sin(2*PI*196*t)+0.15*sin(2*PI*293.66*t)+0.05*sin(2*PI*392*t)";default:return"0"}}
function sfxInput(type:string,duration:number){const d=duration.toFixed(2);switch(type){case"whoosh":return`anoisesrc=color=pink:amplitude=0.18:duration=${d},highpass=f=500,lowpass=f=5000,afade=t=in:d=${Math.min(0.12,duration/2).toFixed(2)},afade=t=out:st=${Math.max(0.01,duration-0.14).toFixed(2)}:d=0.14`;case"pop":return`sine=frequency=720:duration=${d},afade=t=out:st=${Math.max(0.01,duration-0.12).toFixed(2)}:d=0.12`;case"ding":return`sine=frequency=880:duration=${d},afade=t=out:st=${Math.max(0.01,duration-0.18).toFixed(2)}:d=0.18`;case"crowd":return`anoisesrc=color=brown:amplitude=0.08:duration=${d},lowpass=f=900,afade=t=in:d=0.06,afade=t=out:st=${Math.max(0.01,duration-0.12).toFixed(2)}:d=0.12`;case"record-scratch":return`anoisesrc=color=white:amplitude=0.28:duration=${d},highpass=f=1000,lowpass=f=7000,afade=t=out:st=${Math.max(0.01,duration-0.08).toFixed(2)}:d=0.08`;default:return`sine=frequency=90:duration=${d},afade=t=out:st=${Math.max(0.01,duration-0.12).toFixed(2)}:d=0.12`}}
async function run(args:string[]){await execFileAsync(ffmpeg,["-y","-hide_banner","-loglevel","error",...args],{maxBuffer:20*1024*1024})}

export async function POST(request:Request){const workDir=path.join(process.cwd(),"data","renders",`.work-${crypto.randomUUID()}`);try{const body=await request.json() as{orderId?:string;clips?:ClipInput[];plan?:Plan};const clips=Array.isArray(body.clips)?body.clips:[];const plan=body.plan||{};const segments=Array.isArray(plan.clipSequence)?plan.clipSequence:[];if(!clips.length||!segments.length)return NextResponse.json({error:"AI returned no usable edit segments."},{status:422});await mkdir(workDir,{recursive:true});const byName=new Map(clips.map(c=>[c.originalName.toLowerCase(),c]));const transitions=new Map((plan.transitions||[]).map(t=>[t.afterClip.toLowerCase(),t.type]));const segmentFiles:string[]=[];let totalDuration=0;
for(let i=0;i<Math.min(segments.length,9);i++){const seg=segments[i];const clip=byName.get(String(seg.clip).toLowerCase())||clips.find(c=>c.originalName.toLowerCase().includes(String(seg.clip).toLowerCase()))||clips[0];const input=sourcePath(clip);try{await readFile(input)}catch{throw new Error(`Uploaded clip not found: ${clip.originalName}`)}const sourceDuration=clamp(Number(seg.endSeconds)-Number(seg.startSeconds),0.25,30);const speed=clamp(Number(seg.speed??1),0.65,1.35);const outputDuration=sourceDuration/speed;const output=path.join(workDir,`segment-${String(i).padStart(2,"0")}.mp4`);const audio=await hasAudio(input);const vf=videoFilter(seg,plan.colorPreset||"natural",transitions.get(clip.originalName.toLowerCase()),sourceDuration);if(audio){await run(["-ss",String(Math.max(0,Number(seg.startSeconds)||0)),"-t",sourceDuration.toFixed(3),"-i",input,"-vf",vf,"-af",`atempo=${speed.toFixed(3)}`,"-map","0:v:0","-map","0:a:0","-c:v","libx264","-preset","veryfast","-crf","19","-pix_fmt","yuv420p","-r","30","-c:a","aac","-b:a","160k","-ar","48000","-ac","2","-movflags","+faststart",output])}else{await run(["-ss",String(Math.max(0,Number(seg.startSeconds)||0)),"-t",sourceDuration.toFixed(3),"-i",input,"-f","lavfi","-t",outputDuration.toFixed(3),"-i","anullsrc=r=48000:cl=stereo","-vf",vf,"-map","0:v:0","-map","1:a:0","-c:v","libx264","-preset","veryfast","-crf","19","-pix_fmt","yuv420p","-r","30","-c:a","aac","-b:a","160k","-ar","48000","-ac","2","-shortest","-movflags","+faststart",output])}segmentFiles.push(output);totalDuration+=outputDuration}
if(!segmentFiles.length)throw new Error("No renderable AI segments were produced.");const concatList=path.join(workDir,"concat.txt");await writeFile(concatList,segmentFiles.map(file=>`file '${file.replace(/'/g,"'\\''")}'`).join("\n"),"utf8");const concatFile=path.join(workDir,"assembled.mp4");await run(["-f","concat","-safe","0","-i",concatList,"-c","copy","-movflags","+faststart",concatFile]);
const texts:TextOverlay[]=[...(plan.textOverlays||[])];if(plan.hookEnabled!==false&&plan.hook&&!texts.some(t=>t.kind==="hook"))texts.unshift({text:plan.hook,startSeconds:0.25,endSeconds:2,kind:"hook",position:"top",style:"bold",animation:"pop"});for(const caption of plan.captions||[])if(caption.text)texts.push({text:caption.text,startSeconds:Number(caption.startSeconds??0),endSeconds:Number(caption.endSeconds??1.5),kind:"caption",position:caption.placement?.includes("top")?"top":caption.placement?.includes("bottom")?"bottom":"center",style:caption.style||"clean",animation:"fade"});const textGraph=textFilter(texts,totalDuration);const musicMood=plan.musicMood&&plan.musicMood!=="none"?plan.musicMood:"none";const sfx=(plan.sfx||[]).slice(0,8);const needsAudioMix=musicMood!=="none"||sfx.length>0;const finalName=`${body.orderId||"editio"}-${Date.now().toString(36)}-preview.mp4`;const finalPath=path.join(process.cwd(),"data","renders",finalName);await mkdir(path.dirname(finalPath),{recursive:true});
if(!needsAudioMix){await run(["-i",concatFile,"-filter_complex",textGraph.graph,"-map",textGraph.map,"-map","0:a:0","-c:v","libx264","-preset","veryfast","-crf","19","-pix_fmt","yuv420p","-r","30","-c:a","aac","-b:a","160k","-ar","48000","-ac","2","-movflags","+faststart",finalPath])}else{const args:string[]=["-i",concatFile];if(musicMood!=="none")args.push("-f","lavfi","-i",`aevalsrc=${musicExpression(musicMood)}:s=48000:d=${Math.max(1,totalDuration).toFixed(3)}`);const sfxStartIndex=musicMood!=="none"?2:1;sfx.forEach(effect=>{const duration=clamp(Number(effect.durationSeconds??0.18),0.08,0.7);args.push("-f","lavfi","-i",sfxInput(effect.type,duration))});const audioInputs=1+(musicMood!=="none"?1:0)+sfx.length;const audioParts=["[0:a]volume=1.0[base]"];const mixLabels=["[base]"];if(musicMood!=="none"){const vol=clamp(Number(plan.musicIntensity??0.18),0.04,0.32);audioParts.push(`[1:a]volume=${vol.toFixed(3)}[music]`);mixLabels.push("[music]")}sfx.forEach((effect,index)=>{const inputIndex=sfxStartIndex+index;const delay=Math.round(clamp(Number(effect.timeSeconds||0),0,totalDuration)*1000);const vol=clamp(Number(effect.intensity??0.65),0.05,1);audioParts.push(`[${inputIndex}:a]adelay=${delay}:all=1,volume=${vol.toFixed(3)}[sfx${index}]`);mixLabels.push(`[sfx${index}]`)});audioParts.push(`${mixLabels.join("")}amix=inputs=${audioInputs}:duration=first:dropout_transition=0[aout]`);args.push("-filter_complex",`${textGraph.graph};${audioParts.join(";")}`,"-map",textGraph.map,"-map","[aout]","-c:v","libx264","-preset","veryfast","-crf","19","-pix_fmt","yuv420p","-r","30","-c:a","aac","-b:a","160k","-ar","48000","-ac","2","-movflags","+faststart",finalPath]);await run(args)}
return NextResponse.json({ok:true,url:`/api/render/file?name=${encodeURIComponent(finalName)}`,usedAiCuts:true,aiCutCount:segmentFiles.length,features:{smartText:texts.length>0,music:musicMood!=="none",sfx:sfx.length,slowMotion:segments.some(s=>Number(s.speed??1)<0.9),smartReframe:segments.some(s=>Number(s.zoom??1)!==1||s.zoomDirection),color:plan.colorPreset||"natural"}})}catch(error){const message=error instanceof Error?error.message:"AI draft rendering failed.";return NextResponse.json({error:message},{status:500})}}
