"use client";

import Link from "next/link";
import { ChangeEvent, DragEvent, useState } from "react";
import { createOrder, updateOrder } from "../../../lib/orders";
import { extractVideoFrames, type VideoFrame } from "../../../lib/video-analysis";
import { consumeFreeAiCredit, hasFreeAiCredit } from "../../../lib/session";
import styles from "./edit.module.css";

type Clip={id:string;file:File;url:string};
type UploadResponse={ok?:boolean;error?:string;files?:Array<{originalName:string;url:string}>};
type AIResponse={ok?:boolean;error?:string;plan?:unknown};
type RenderResponse={ok?:boolean;error?:string;url?:string};
const guides:Record<string,string>={Cricket:"Make a high-energy cricket Reel around the REAL main event. If there is a wicket, dismissal, catch, boundary or decisive result, that actual play is the hero — not just the celebration. Build setup → delivery/action → result → reaction/replay when supported. Preserve bowler + batsman + pitch/wicket context. Remove dead time, duplicates and accidental tails.",Fashion:"Make a stylish fashion Reel around the strongest real reveal, movement, outfit detail or final look. Keep pacing premium and remove awkward pauses and duplicate shots.",Travel:"Make an immersive travel Reel around the strongest real experience. Use establishing context, movement, detail and a memorable ending. Remove walking/dead time and empty frames.",Food:"Make an appetizing Reel around the strongest real preparation, texture, reveal or final food shot. Keep cuts tight and end on the most satisfying real visual.",Fitness:"Make a motivating Reel around the strongest real movement, effort or result. Build setup → action → payoff and remove rest/dead time.",Beauty:"Make a polished beauty Reel around the real transformation or final look. Build before → action/detail → reveal when supported and remove dead time.",Lifestyle:"Make a modern lifestyle Reel around the strongest real moment/payoff with a natural mini-story and satisfying ending.",Gaming:"Make an energetic gaming Reel around the strongest real clutch, win, fail or reaction. Build tension toward the payoff and remove menus/dead time.",Business:"Make a sharp creator/business Reel around the strongest real useful moment, product/work action or payoff. Keep it concise and credible.",Other:"Use your best editorial judgement to find the strongest real moment and build a concise story around it. Never invent anything not visible."};
const categories=Object.keys(guides);const vibes=["Fast & punchy","Cinematic","Clean & premium","Funny","Emotional","Hype"];

export default function CreatorEdit(){
  const [step,setStep]=useState(1);const [clips,setClips]=useState<Clip[]>([]);const [dragging,setDragging]=useState(false);const [vibe,setVibe]=useState("Fast & punchy");const [category,setCategory]=useState("Cricket");const [direction,setDirection]=useState(guides.Cricket);const [reference,setReference]=useState("");const [error,setError]=useState("");const [uploading,setUploading]=useState(false);const [submitted,setSubmitted]=useState(false);const [orderId,setOrderId]=useState("");const [aiResult,setAiResult]=useState<"ready"|"failed"|"not_started">("not_started");const [renderResult,setRenderResult]=useState<"ready"|"failed"|"not_started">("not_started");const [retrying,setRetrying]=useState(false);const [retryUsed,setRetryUsed]=useState(false);const [uploaded,setUploaded]=useState<Array<{originalName:string;url:string}>>([]);const [frames,setFrames]=useState<VideoFrame[]>([]);
  function addFiles(files:FileList|File[]){const incoming=Array.from(files).filter(f=>f.type.startsWith("video/"));setClips(c=>[...c,...incoming.map(file=>({id:`${file.name}-${file.size}-${crypto.randomUUID()}`,file,url:URL.createObjectURL(file)}))]);}
  function onFileChange(e:ChangeEvent<HTMLInputElement>){if(e.target.files)addFiles(e.target.files);e.target.value=""}function onDrop(e:DragEvent<HTMLLabelElement>){e.preventDefault();setDragging(false);if(e.dataTransfer.files.length)addFiles(e.dataTransfer.files)}
  function removeClip(id:string){setClips(c=>{const x=c.find(v=>v.id===id);if(x)URL.revokeObjectURL(x.url);return c.filter(v=>v.id!==id)})}function moveClip(i:number,d:-1|1){setClips(c=>{const t=i+d;if(t<0||t>=c.length)return c;const n=[...c];[n[i],n[t]]=[n[t],n[i]];return n})}function selectCategory(value:string){setCategory(value);setDirection(guides[value])}
  async function runAi(id:string,files:Array<{originalName:string;url:string}>,frameData:VideoFrame[]){const response=await fetch("/api/ai/analyze-v2",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({orderId:id,editType:"AI Edit",format:"Instagram Reel",vibe,category,creativeDirection:direction.trim(),hookEnabled:true,hookText:"",reference:reference.trim(),frames:frameData})});const data=await response.json() as AIResponse;if(!response.ok||!data.plan)throw new Error(data.error||"AI footage analysis failed.");updateOrder(id,{status:"processing",aiStatus:"ready",aiPlan:data.plan as never,renderStatus:"rendering"});setAiResult("ready");const render=await fetch("/api/render/draft",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({orderId:id,clips:files,plan:data.plan})});const renderData=await render.json() as RenderResponse;if(!render.ok||!renderData.url)throw new Error(renderData.error||"AI Reel rendering failed.");updateOrder(id,{status:"in_review",renderStatus:"ready",draftUrl:renderData.url});setRenderResult("ready")}
  async function submit(){if(!clips.length||uploading)return;if(!hasFreeAiCredit()){setError("Your free AI Reel has already been used. Buy an AI edit credit for another Reel.");return}if(!direction.trim()){setError("Add a little creative direction or keep the suggested direction.");return}setError("");setUploading(true);setAiResult("not_started");setRenderResult("not_started");try{const form=new FormData();clips.forEach(c=>form.append("files",c.file,c.file.name));const uploadResponse=await fetch("/api/uploads",{method:"POST",body:form});const uploadData=await uploadResponse.json() as UploadResponse;if(!uploadResponse.ok||!uploadData.files?.length)throw new Error(uploadData.error||"Could not upload your footage.");const uploadedFiles=uploadData.files.map(f=>({originalName:f.originalName,url:f.url}));const order=createOrder({mode:"ai",modeLabel:"AI Edit",format:"Instagram Reel",vibe,category,creativeDirection:direction.trim(),hookEnabled:true,hookText:"",brief:direction.trim(),reference:reference.trim(),includeHook:true,includeCaptions:true,clipNames:uploadedFiles.map(f=>f.originalName),clipUrls:uploadedFiles.map(f=>f.url),clipCount:uploadedFiles.length,aiStatus:"queued",renderStatus:"rendering"});if(!order)throw new Error("Could not create the edit order.");setOrderId(order.id);setUploaded(uploadedFiles);consumeFreeAiCredit();try{const frameData:VideoFrame[]=[];for(const clip of clips)frameData.push(...await extractVideoFrames(clip.file.name,clip.url));if(!frameData.length)throw new Error("Could not read frames from your footage.");setFrames(frameData);await runAi(order.id,uploadedFiles,frameData)}catch(e){const message=e instanceof Error?e.message:"AI editing failed.";updateOrder(order.id,{status:"processing",aiStatus:"failed",renderStatus:"failed",aiError:message});setAiResult("failed");setRenderResult("failed");setError(message)}setSubmitted(true)}catch(e){setError(e instanceof Error?e.message:"Something went wrong. Please try again.")}finally{setUploading(false)}}
  async function retryAi(){if(retrying||retryUsed||!orderId||!frames.length||!uploaded.length)return;setRetryUsed(true);setRetrying(true);setError("");try{await runAi(orderId,uploaded,frames)}catch(e){const message=e instanceof Error?e.message:"AI retry failed.";updateOrder(orderId,{renderStatus:"failed",aiError:message});setRenderResult("failed");setError(message)}finally{setRetrying(false)}}
  if(submitted)return <main className={styles.page}><header className={styles.nav}><Link className={styles.logo} href="/creator/dashboard">EDIT<span>IO</span></Link><span className={styles.successTag}>{renderResult==="ready"?"REEL READY ✦":"AI EDIT ✦"}</span><Link className={styles.exit} href={`/creator/orders/${orderId}`}>Open my edit ↗</Link></header><section className={styles.successShell}><div className={styles.successBadge}>{renderResult==="ready"?"✦ YOUR AI REEL IS READY":"✦ EDITIO IS WORKING"}</div><h1>{renderResult==="ready"?<>Your Reel is<br/><em>ready.</em></>:<>We&apos;ve got<br/><em>your Reel.</em></>}</h1><p>{renderResult==="ready"?"EDITIO found the story, built the cuts and rendered the full Reel with the smart finishing touches.":aiResult==="ready"?"The AI edit plan is ready, but the renderer needs another attempt.":"Your footage is safe. The AI editor needs another attempt."}</p>{error&&<div className={styles.submitError}>{error}</div>}<div className={styles.orderCard}><div><span>ORDER</span><strong>{orderId}</strong></div><div><span>EDIT TYPE</span><b>AI Edit</b></div><div><span>STATUS</span><b className={renderResult==="ready"?styles.statusPill:styles.statusPillMuted}>{renderResult==="ready"?"Ready to watch":"Needs attention"}</b></div></div>{renderResult==="failed"&&!retryUsed&&<button className={styles.successButton} onClick={retryAi} disabled={retrying}>{retrying?"Retrying AI…":"Retry AI — 1 retry left"}<span>↻</span></button>}<Link href={`/creator/orders/${orderId}`} className={styles.successButton}>{renderResult==="ready"?"Watch my Reel":"Open my edit"}<span>↗</span></Link></section></main>;
  return <main className={styles.page}><header className={styles.nav}><Link className={styles.logo} href="/creator/dashboard">EDIT<span>IO</span></Link><div className={styles.stepper}><span className={step>=1?styles.active:""}>01</span><i/><span className={step>=2?styles.active:""}>02</span><i/><span className={step>=3?styles.active:""}>03</span></div><Link className={styles.exit} href="/creator/dashboard">Save &amp; exit</Link></header><section className={styles.shell}><div className={styles.heading}><div className={styles.eyebrow}>NEW AI EDIT / 001</div><h1>Let&apos;s make<br/><em>your Reel.</em></h1><p>{step===1?"Tell EDITIO the vibe. The AI decides the story, hero moment and exact cuts.":step===2?"Upload everything. EDITIO will study the actual frames and build the Reel.":"One last look before we put your edit in motion."}</p></div>
  {step===1&&<div className={styles.briefCard}><div className={styles.briefHead}><div><div className={styles.eyebrow}>AI EDITOR</div><h2>Set the direction.</h2></div><span className={styles.readyPill}>AI DOES THE REST</span></div><div className={styles.fields}><label>What are you making?<select value={category} onChange={e=>selectCategory(e.target.value)}>{categories.map(c=><option key={c}>{c}</option>)}</select></label><label>Editing energy<select value={vibe} onChange={e=>setVibe(e.target.value)}>{vibes.map(v=><option key={v}>{v}</option>)}</select></label><label className={styles.full}>Creative direction<textarea value={direction} onChange={e=>setDirection(e.target.value)} placeholder="Tell EDITIO anything important. You can also leave the AI suggestion as-is."/></label><label className={styles.full}>Reference Reel / style link <input value={reference} onChange={e=>setReference(e.target.value)} placeholder="Optional Instagram / YouTube / reference URL"/></label></div>{error&&<div className={styles.submitError}>{error}</div>}<div className={styles.briefActions}><span className={styles.back}>AI decides what actually deserves screen time.</span><button className={styles.continue} onClick={()=>{setError("");setStep(2)}}>Continue to footage <span>↗</span></button></div></div>}
  {step===2&&<div className={styles.briefCard}><div className={styles.briefHead}><div><div className={styles.eyebrow}>02 / FOOTAGE</div><h2>Drop the clips.</h2></div><span className={styles.clipCount}>{clips.length} {clips.length===1?"clip":"clips"}</span></div><label className={`${styles.upload} ${dragging?styles.uploadDragging:""}`} onDragOver={e=>{e.preventDefault();setDragging(true)}} onDragLeave={()=>setDragging(false)} onDrop={onDrop}><input type="file" accept="video/*" multiple onChange={onFileChange}/><span>＋</span><b>Drop your videos here</b><small>or click to browse · multiple clips supported</small></label>{clips.length>0&&<div className={styles.clipList}>{clips.map((clip,i)=><div className={styles.clip} key={clip.id}><div className={styles.clipPreview}><video src={clip.url} muted playsInline/></div><div className={styles.clipInfo}><b>{clip.file.name}</b><small>{(clip.file.size/1024/1024).toFixed(1)} MB · clip {i+1}</small></div><div className={styles.clipActions}><button onClick={()=>moveClip(i,-1)} disabled={i===0}>↑</button><button onClick={()=>moveClip(i,1)} disabled={i===clips.length-1}>↓</button><button onClick={()=>removeClip(clip.id)}>×</button></div></div>)}</div>}{error&&<div className={styles.submitError}>{error}</div>}<div className={styles.briefActions}><button className={styles.back} onClick={()=>setStep(1)}>← Back</button><button className={styles.continue} disabled={!clips.length||uploading} onClick={()=>setStep(3)}>Review edit <span>↗</span></button></div></div>}
  {step===3&&<div className={styles.reviewCard}><div className={styles.reviewHeader}><div><div className={styles.eyebrow}>03 / REVIEW</div><h2>Ready to let AI cut?</h2></div><span className={styles.readyPill}>FULL REEL</span></div><div className={styles.reviewGrid}><div className={styles.reviewMode}><div className={styles.reviewIcon}>✦</div><div><small>EDIT TYPE</small><strong>AI Edit</strong><p>AI decides the main moment, pacing, clip order and finishing details.</p></div></div><div><small>STYLE</small><strong>{category}</strong><p>{vibe} · Instagram Reel · 9:16</p></div><div><small>AUTOMATIC FINISHING</small><strong>A → Z</strong><p>Hero story · hook · editorial text · captions · music mood · SFX · slow-mo · smart framing · color · ending</p></div><div><small>REFERENCE</small><p className={styles.referenceText}>{reference||"No reference — AI will use its own editorial judgement."}</p></div></div>{error&&<div className={styles.submitError}>{error}</div>}<div className={styles.reviewActions}><button className={styles.back} onClick={()=>setStep(2)}>← Back to footage</button><button className={styles.submitButton} onClick={submit} disabled={uploading}>{uploading?"EDITIO IS CUTTING…":"Create my Reel"}<span>✦</span></button></div></div>}
  </section></main>;
}
